/* @generated by cbindgen from src/ffi/ — DO NOT EDIT. Regenerate via `cargo build`. */

#ifndef SHARPDX_H
#define SHARPDX_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#define SDE_OK 0

#define SDE_ERR -1

#define SDE_ERR_PANIC -2

#define SDE_ERR_ARGS -3

#define SDE_ERR_NOT_FOUND -4

#define SDE_ERR_EXISTS -5

#define SDE_ERR_DISK_FULL -6

#define SDE_ERR_NOT_FORMATTED -7

#define SDE_ERR_PROTECTED -8

#define SDE_ERR_BAD_NAME -9

#define SDE_ERR_CORRUPT -10

#define SDE_ERR_DIRECTORY_FULL -11

/*
 Bytes in one floppy side (16 tracks × 8 sectors × 512 bytes).
 */
#define SDE_DISK_SIDE_SIZE 65536

/*
 Directory entries per side.
 */
#define SDE_DISK_MAX_ENTRIES 48

/*
 `flags`: replace an existing file / delete write-protected files.
 */
#define SDE_DISK_FORCE 1

/*
 `run_addr` for `sde_disk_put` in machine mode: no auto-start.
 */
#define SDE_DISK_NO_RUN 4294967295

/*
 `SdeFileInfo::problems`: the payload is shorter than the header says.
 */
#define SDE_PROBLEM_TRUNCATED 1

/*
 Bytes follow the payload.
 */
#define SDE_PROBLEM_TRAILING 2

/*
 `00` bytes precede the header.
 */
#define SDE_PROBLEM_LEADING_NOISE 4

/*
 Starts with header magic, but no complete header with a known type follows.
 */
#define SDE_PROBLEM_HEADER_CUT 8

/*
 Tokenized BASIC that doesn't de-tokenize, or Reserve Area / Variables that don't decode.
 */
#define SDE_PROBLEM_BAD_PAYLOAD 16

/*
 The problems that make a file unusable (`sde_file_kind` reports these as `damaged`).
 */
#define SDE_PROBLEM_FATAL 25

/*
 Bytes in `SdeFileInfo::name`: 16 CP437 characters as UTF-8, plus the NUL.
 */
#define SDE_FILE_NAME_SIZE 49

/*
 Not a RIFF/WAVE file (or a WAV encoding that can't be read).
 */
#define SDE_ERR_WAV_FORMAT -12

/*
 A WAV with no PC-1500 / PC-1600 tape signal on it.
 */
#define SDE_ERR_WAV_NO_SIGNAL -13

/*
 A tape file was found but failed its checksums: it could not be decoded safely.
 */
#define SDE_ERR_WAV_CORRUPT -14

/*
 Content this library can't put on (or take off) a tape, e.g. a PC-1500 data file.
 */
#define SDE_ERR_WAV_UNSUPPORTED -15

/*
 `leader_ms` for `sde_wav_encode`: the default short leader (about 2 s on the
 PC-1500, 3 s on the PC-1600).
 */
#define SDE_WAV_LEADER_DEFAULT 0

/*
 `leader_ms` for `sde_wav_encode`: the ROMs' own, long leader.
 */
#define SDE_WAV_LEADER_ROM 4294967295

/*
 Detected input content kind.
 */
typedef enum {
    SDE_CONTENT_UNKNOWN = 0,
    SDE_CONTENT_ASCII_BASIC = 1,
    SDE_CONTENT_CE158_BASIC = 2,
    SDE_CONTENT_PC1600_BASIC = 3,
    /*
     Plain text that is not a BASIC listing (every character in the Sharp set).
     */
    SDE_CONTENT_TEXT = 4,
} SdeContent;

/*
 Target machine family.
 */
typedef enum {
    SDE_DEVICE_PC1500 = 0,
    SDE_DEVICE_PC1600 = 1,
} SdeDevice;

/*
 How `sde_disk_get` returns a file.
 */
typedef enum {
    /*
     The natural host form: BASIC de-tokenized to a UTF-8 listing, ASCII files as
     UTF-8 text, machine code and unknown data unchanged.
     */
    SDE_DISK_GET_MODE_AUTO = 0,
    /*
     Unchanged, header included (BASIC stays tokenized).
     */
    SDE_DISK_GET_MODE_BINARY = 1,
    /*
     Like `Binary`, without the 16-byte header.
     */
    SDE_DISK_GET_MODE_PAYLOAD = 2,
    /*
     The stored bytes, no interpretation at all.
     */
    SDE_DISK_GET_MODE_RAW = 3,
} SdeDiskGetMode;

/*
 What a stored file holds (from its content; the directory does not record it).
 */
typedef enum {
    SDE_DISK_KIND_UNKNOWN = 0,
    /*
     Tokenized BASIC behind a PC-1600 header.
     */
    SDE_DISK_KIND_BASIC = 1,
    /*
     Machine language behind a PC-1600 header.
     */
    SDE_DISK_KIND_MACHINE = 2,
    /*
     A BASIC program saved as ASCII.
     */
    SDE_DISK_KIND_ASCII_BASIC = 3,
    /*
     Any other ASCII file.
     */
    SDE_DISK_KIND_TEXT = 4,
} SdeDiskKind;

/*
 How `sde_disk_put` turns the input into a stored file.
 */
typedef enum {
    /*
     By content: a BASIC listing is tokenized, text becomes a PC-1600 ASCII file
     (CP437, CRLF, `1A`), a file with a PC-1600 header is stored unchanged; anything
     else is an error.
     */
    SDE_DISK_PUT_MODE_AUTO = 0,
    /*
     A BASIC listing stored as an ASCII program file (`SAVE "…",A`).
     */
    SDE_DISK_PUT_MODE_ASCII_LISTING = 1,
    /*
     Headerless machine code, wrapped in a header with `start_addr`/`run_addr`.
     */
    SDE_DISK_PUT_MODE_MACHINE = 2,
    /*
     Stored exactly as given.
     */
    SDE_DISK_PUT_MODE_RAW = 3,
    /*
     Tokenized as a BASIC listing even if detection took it for plain text (the
     override for a misdetect); fails if it does not tokenize.
     */
    SDE_DISK_PUT_MODE_TOKENIZE = 4,
} SdeDiskPutMode;

/*
 Line ending for a de-tokenized listing (`sde_detokenize` / `sde_convert`).
 Ignored when tokenizing — `CR` and `CRLF` input are always accepted.
 */
typedef enum {
    /*
     Host default: `\r\n` on Windows, `\n` elsewhere.
     */
    SDE_LINE_ENDING_PLATFORM = 0,
    /*
     `\n` (LF).
     */
    SDE_LINE_ENDING_LF = 1,
    /*
     `\r\n` (CRLF).
     */
    SDE_LINE_ENDING_CR_LF = 2,
    /*
     `\r` (CR) — the PC-1500's own line terminator.
     */
    SDE_LINE_ENDING_CR = 3,
} SdeLineEnding;

/*
 How a `#SEGMENT` marker line tokenizes (`sde_tokenize` only; a device saving
 multiple GOSUB "LABEL" program segments together). `Wire` is the 3-byte sequence
 `0xFF 0x00 0x00` actually sent over `SAVE "COM1:"`. `Memory` is the bare `0xFF`
 the ROM's own serial receiver actually stores into the program area -- use this
 when building bytes for a direct RAM poke rather than a real/emulated serial
 transfer (confirmed against a real PC-1600's `LOAD "COM1:"` pointers: BASPRG_END
 comes out exactly 2 bytes short of the `Wire` form, once per marker).
 */
typedef enum {
    SDE_SEGMENT_MARKER_WIRE = 0,
    SDE_SEGMENT_MARKER_MEMORY = 1,
} SdeSegmentMarker;

/*
 Which machine / interface a tape is for.
 */
typedef enum {
    /*
     PC-1500 / PC-1500A with CE-150.
     */
    SDE_TAPE_FORMAT_PC1500_CE150 = 0,
    /*
     PC-1600 with CE-1600P, MODE 0.
     */
    SDE_TAPE_FORMAT_PC1600_CE1600P = 1,
} SdeTapeFormat;

/*
 What a tape file holds.
 */
typedef enum {
    SDE_TAPE_KIND_BASIC = 0,
    SDE_TAPE_KIND_MACHINE = 1,
    SDE_TAPE_KIND_RESERVE = 2,
    SDE_TAPE_KIND_DEF_KEYS = 3,
    SDE_TAPE_KIND_DATA = 4,
    SDE_TAPE_KIND_ASCII = 5,
} SdeTapeKind;

/*
 One directory entry.
 */
typedef struct {
    /*
     `NAME.EXT`, NUL-terminated.
     */
    char name[13];
    /*
     Attribute byte (bit 0 write-protected, bit 2 hidden).
     */
    uint8_t attr;
    uint8_t month;
    uint8_t day;
    uint8_t hour;
    uint8_t minute;
    uint8_t second;
    /*
     Size in bytes as stored (a header included).
     */
    uint32_t size;
    SdeDiskKind kind;
    /*
     Machine code only: 24-bit load / run address (bank in bits 16-23).
     */
    uint32_t load_addr;
    uint32_t run_addr;
} SdeDirEntry;

/*
 A directory timestamp. The PC-1600 clock has no year.
 */
typedef struct {
    uint8_t month;
    uint8_t day;
    uint8_t hour;
    uint8_t minute;
    uint8_t second;
} SdeDiskTime;

/*
 What a buffer holds (`sde_file_info`).
 */
typedef struct {
    /*
     Static token, as `sde_file_kind` returns it but never `damaged`: check `problems`.
     */
    const char *kind;
    /*
     `SDE_PROBLEM_*` bits.
     */
    uint32_t problems;
    /*
     First payload byte in the input: after the header, `0` for headerless content.
     */
    size_t payload_offset;
    /*
     Payload bytes present in the input (never past its end, even when truncated).
     */
    size_t payload_len;
    /*
     `ml-*`: load address (PC-1600: bank in bits 16-23). Else `0`.
     */
    uint32_t load_addr;
    /*
     `ml-*`: run address. Else `0`.
     */
    uint32_t run_addr;
    /*
     `ml-*`: `1` if `run_addr` is a real auto-start, else `0`.
     */
    int32_t autorun;
    /*
     CE-158 header filename, or the name in SDAR / SDAV text; UTF-8, NUL-terminated,
     empty if none.
     */
    char name[SDE_FILE_NAME_SIZE];
} SdeFileInfo;

/*
 One file decoded from a tape.
 */
typedef struct {
    SdeTapeFormat format;
    SdeTapeKind kind;
    /*
     Name on the tape, UTF-8, NUL-terminated.
     */
    char name[SDE_FILE_NAME_SIZE];
    /*
     Machine code: load / entry address as on the tape (PC-1600: bank in bits
     16-23). Else `0`.
     */
    uint32_t load_addr;
    uint32_t run_addr;
    /*
     Machine code: `1` if `run_addr` is a real auto-start.
     */
    int32_t autorun;
    /*
     Payload bytes (without header).
     */
    size_t payload_len;
    /*
     Where the file starts on the tape, milliseconds.
     */
    uint32_t start_ms;
    /*
     Measured tape speed, per mille of nominal (`1000` = exact, `1050` = 5 % fast).
     */
    uint32_t speed_permille;
} SdeWavFile;



#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Crate version, static NUL-terminated string.
 */
const char *sde_version(void);

/*
 Last error message on this thread. Never NULL; empty string if no error.
 */
const char *sde_last_error(void);

/*
 Release a buffer returned via an `out` / `out_len` pair.

 # Safety
 `ptr`/`len` must be exactly what a prior `sde_*` call wrote, and must be freed once.
 */
void sde_buf_free(uint8_t *ptr, size_t len);

/*
 Detect the content kind of `in`. Writes `*out_kind`.

 # Safety
 `in`/`in_len` describe a readable buffer; `out_kind` is a writable `SdeContent`.
 */
int32_t sde_detect(const uint8_t *input, size_t in_len, SdeContent *out_kind);

/*
 ASCII BASIC bytes -> tokenized payload. `with_header != 0` prepends the serial
 header. `segment_marker` selects how a `#SEGMENT` line renders -- see
 [`SdeSegmentMarker`] (`SDE_SEGMENT_MARKER_WIRE` is what `SAVE "COM1:"` sends).

 # Safety
 Pointer/length pairs must describe readable buffers; `name` is NULL or a C string;
 `out`/`out_len` are writable.
 */
int32_t sde_tokenize(SdeDevice device,
                     int with_header,
                     SdeSegmentMarker segment_marker,
                     const char *name,
                     const uint8_t *input,
                     size_t in_len,
                     uint8_t **out,
                     size_t *out_len);

/*
 Tokenized bytes -> ASCII BASIC (UTF-8). Accepts a CE-158 / PC-1600 header (device
 then taken from it) or a bare payload (uses `device`). `line_ending` sets the
 listing's line terminator (`SDE_LINE_ENDING_PLATFORM` = the host default).

 # Safety
 As `sde_tokenize`.
 */
int32_t sde_detokenize(SdeDevice device,
                       const uint8_t *input,
                       size_t in_len,
                       SdeLineEnding line_ending,
                       uint8_t **out,
                       size_t *out_len);

/*
 Content-driven convert (mirrors the CLI): picks direction from `in`. Writes
 `*out_kind` with the detected input kind when non-NULL. `line_ending` sets the
 line terminator of a de-tokenized listing (`SDE_LINE_ENDING_PLATFORM` = the
 host default); it is ignored when the input is ASCII BASIC.

 # Safety
 As `sde_tokenize`; `out_kind` is NULL or writable.
 */
int32_t sde_convert(SdeDevice device,
                    const char *name,
                    const uint8_t *input,
                    size_t in_len,
                    SdeLineEnding line_ending,
                    uint8_t **out,
                    size_t *out_len,
                    SdeContent *out_kind);

/*
 List the files on a side into `entries` (up to `capacity`; `SDE_DISK_MAX_ENTRIES`
 always suffices). `*out_count` receives the number of files, `*out_free_bytes` (if
 non-NULL) the free space. An unformatted side is `SDE_ERR_NOT_FORMATTED`.

 # Safety
 `side` points to `side_len` readable bytes; `entries` to `capacity` writable
 entries (or NULL with `capacity == 0`); `out_count` is writable.
 */
int32_t sde_disk_list(const uint8_t *side_buf,
                      size_t side_len,
                      SdeDirEntry *entries,
                      size_t capacity,
                      size_t *out_count,
                      uint32_t *out_free_bytes);

/*
 Read file `name` (`NAME.EXT`, case-insensitive) from a side, converted per `mode`.
 `line_ending` applies to listings and text in `Auto` mode. `*out`/`*out_len` receive
 a buffer to release with `sde_buf_free`; `*out_kind` (if non-NULL) the file's kind.

 # Safety
 As `sde_disk_list`; `name` is a C string; `out`/`out_len` are writable.
 */
int32_t sde_disk_get(const uint8_t *side_buf,
                     size_t side_len,
                     const char *name,
                     SdeDiskGetMode mode,
                     SdeLineEnding line_ending,
                     uint8_t **out,
                     size_t *out_len,
                     SdeDiskKind *out_kind);

/*
 Store `input` as `name` on a side, converted per `mode` (see [`SdeDiskPutMode`]).
 `start_addr`/`run_addr` are used in `Machine` mode only (24-bit, bank in bits 16-23;
 `run_addr == SDE_DISK_NO_RUN` = no auto-start). `flags` may contain `SDE_DISK_FORCE`
 to replace an existing file. `when` is the directory timestamp, NULL = now (UTC).

 # Safety
 `side_buf` points to `side_len` writable bytes; `name` is a C string; `input`/`in_len`
 describe a readable buffer; `when` is NULL or readable.
 */
int32_t sde_disk_put(uint8_t *side_buf,
                     size_t side_len,
                     const char *name,
                     const uint8_t *input,
                     size_t in_len,
                     SdeDiskPutMode mode,
                     uint32_t start_addr,
                     uint32_t run_addr,
                     uint32_t flags,
                     const SdeDiskTime *when);

/*
 Delete `name_or_pattern` (`NAME.EXT`, or with `*`/`?` wildcards) from a side.
 `*out_deleted` (if non-NULL) receives the number of files deleted; no match is
 `SDE_ERR_NOT_FOUND`. `flags` may contain `SDE_DISK_FORCE` to delete write-protected
 files.

 # Safety
 As `sde_disk_put`; `out_deleted` is NULL or writable.
 */
int32_t sde_disk_delete(uint8_t *side_buf,
                        size_t side_len,
                        const char *name_or_pattern,
                        uint32_t flags,
                        size_t *out_deleted);

/*
 Classify `in` as a one-word token: `basic-ascii`, `basic-pc1500`, `basic-pc1600`,
 `ml-lh5801`, `ml-z80`, `raw-lh5801`, `raw-z80`, `raw`, `reserve`, `reserve-text`,
 `variables`, `variables-text`, `text`, `empty`, `wav-pc1500`, `wav-pc1600`, `wav` —
 or `damaged` if the file has a fatal problem (`SDE_PROBLEM_FATAL`). `raw-*` are
 heuristic CPU guesses. For a cassette WAV (`wav-*`) the other `SdeFileInfo` fields
 describe the first file on the tape; `sde_wav_decode` gets its serial image.
 `*out_kind` receives a static NUL-terminated string: do not free it.

 # Safety
 `in`/`in_len` describe a readable buffer; `out_kind` is writable.
 */
int32_t sde_file_kind(const uint8_t *input, size_t in_len, const char **out_kind);

/*
 Classify `in` and fill `*out` with what a loader needs: the kind token, problem
 flags, where the payload is, the load/run address, and the name. Nothing to free.

 # Safety
 `in`/`in_len` describe a readable buffer; `out` is a writable `SdeFileInfo`.
 */
int32_t sde_file_info(const uint8_t *input, size_t in_len, SdeFileInfo *out);

/*
 Count the files on the tape in `in` that decode safely. `*out_issues` (may be NULL)
 receives the number of files found but *not* decodable (checksum errors,
 unsupported types). Returns `SDE_ERR_WAV_NO_SIGNAL` when nothing at all is on it.

 # Safety
 `in`/`in_len` describe a readable buffer; `out_count` is writable; `out_issues` is
 NULL or writable.
 */
int32_t sde_wav_count(const uint8_t *input, size_t in_len, size_t *out_count, size_t *out_issues);

/*
 Decode file `index` (0-based, in tape order) of the tape in `in` to its serial image
 (CE-158 / PC-1600 header + payload) in `*out` / `*out_len` (free with
 `sde_buf_free`). `*out_file` (may be NULL) receives its description. With no file at
 `index`, the error explains why (e.g. the checksum error of a damaged file).

 # Safety
 `in`/`in_len` describe a readable buffer; `out`/`out_len` are writable; `out_file`
 is NULL or writable.
 */
int32_t sde_wav_decode(const uint8_t *input,
                       size_t in_len,
                       size_t index,
                       uint8_t **out,
                       size_t *out_len,
                       SdeWavFile *out_file);

/*
 Encode a serial image (CE-158 or PC-1600 header + payload: BASIC, machine code, or
 PC-1500 reserve) as a cassette WAV (16-bit mono, `sample_rate` at least 16000) in
 `*out` / `*out_len` (free with
 `sde_buf_free`). The tape format follows the header: CE-158 → PC-1500 / CE-150,
 PC-1600 → CE-1600P. `name` (may be NULL) overrides the file name on the tape;
 `leader_ms` is the lead-in length (`SDE_WAV_LEADER_DEFAULT`, `SDE_WAV_LEADER_ROM`,
 or milliseconds).

 # Safety
 `in`/`in_len` describe a readable buffer; `name` is NULL or a NUL-terminated string;
 `out`/`out_len` are writable.
 */
int32_t sde_wav_encode(const uint8_t *input,
                       size_t in_len,
                       uint32_t sample_rate,
                       uint32_t leader_ms,
                       const char *name,
                       uint8_t **out,
                       size_t *out_len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SHARPDX_H */
