/* @generated by cbindgen from src/ffi/ — DO NOT EDIT. Regenerate via `cargo build`. */

#ifndef SHARPDX_H
#define SHARPDX_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/*
 Low 16 bits of a PC-1600 header's run address meaning "no auto-start" (`BSAVE`'s
 default `&FFFF`). The bank byte is taken from the load address; a bank-0 `BSAVE` in
 Calc-U-1600 writes exactly this header (`… C5 C0 00 FF FF 00 …`).
 */
#define PC1600_NO_AUTORUN 65535

/*
 Bytes per side (16 tracks × 8 sectors × 512 bytes).
 */
#define SIDE_SIZE 65536

#define FORMAT_VERSION 1

/*
 Attribute of a newly written file (bit 5 is always set; nothing else).
 */
#define NEW_FILE_ATTR 32

#define ATTR_PROTECTED 1

#define ATTR_UNKNOWN_I 2

#define ATTR_HIDDEN 4

/*
 Year field of a new file: the PC-1600 ROM writes 6 whatever the date (checked in
 Calc-U-1600 with `DATE$ = "09/22"`, and on `dw.img`).
 */
#define NEW_FILE_YEAR_FIELD 6

#define SDE_OK 0

#define SDE_ERR -1

#define SDE_ERR_PANIC -2

#define SDE_ERR_ARGS -3

#define SDE_ERR_NOT_FOUND -4

#define SDE_ERR_EXISTS -5

#define SDE_ERR_DISK_FULL -6

#define SDE_ERR_NOT_FORMATTED -7

#define SDE_ERR_PROTECTED -8

#define SDE_ERR_BAD_NAME -9

#define SDE_ERR_CORRUPT -10

#define SDE_ERR_DIRECTORY_FULL -11

/*
 Bytes in one floppy side (16 tracks × 8 sectors × 512 bytes).
 */
#define SDE_DISK_SIDE_SIZE 65536

/*
 Directory entries per side.
 */
#define SDE_DISK_MAX_ENTRIES 48

/*
 `flags`: replace an existing file / delete write-protected files.
 */
#define SDE_DISK_FORCE 1

/*
 `run_addr` for `sde_disk_put` in machine mode: no auto-start.
 */
#define SDE_DISK_NO_RUN 4294967295

/*
 Detected input content kind.
 */
typedef enum {
    SDE_CONTENT_UNKNOWN = 0,
    SDE_CONTENT_ASCII_BASIC = 1,
    SDE_CONTENT_CE158_BASIC = 2,
    SDE_CONTENT_PC1600_BASIC = 3,
    /*
     Plain text that is not a BASIC listing (every character in the Sharp set).
     */
    SDE_CONTENT_TEXT = 4,
} SdeContent;

/*
 Target machine family.
 */
typedef enum {
    SDE_DEVICE_PC1500 = 0,
    SDE_DEVICE_PC1600 = 1,
} SdeDevice;

/*
 How `sde_disk_get` returns a file.
 */
typedef enum {
    /*
     The natural host form: BASIC de-tokenized to a UTF-8 listing, ASCII files as
     UTF-8 text, machine code and unknown data unchanged.
     */
    SDE_DISK_GET_MODE_AUTO = 0,
    /*
     Unchanged, header included (BASIC stays tokenized).
     */
    SDE_DISK_GET_MODE_BINARY = 1,
    /*
     Like `Binary`, without the 16-byte header.
     */
    SDE_DISK_GET_MODE_PAYLOAD = 2,
    /*
     The stored bytes, no interpretation at all.
     */
    SDE_DISK_GET_MODE_RAW = 3,
} SdeDiskGetMode;

/*
 What a stored file holds (from its content; the directory does not record it).
 */
typedef enum {
    SDE_DISK_KIND_UNKNOWN = 0,
    /*
     Tokenized BASIC behind a PC-1600 header.
     */
    SDE_DISK_KIND_BASIC = 1,
    /*
     Machine language behind a PC-1600 header.
     */
    SDE_DISK_KIND_MACHINE = 2,
    /*
     A BASIC program saved as ASCII.
     */
    SDE_DISK_KIND_ASCII_BASIC = 3,
    /*
     Any other ASCII file.
     */
    SDE_DISK_KIND_TEXT = 4,
} SdeDiskKind;

/*
 How `sde_disk_put` turns the input into a stored file.
 */
typedef enum {
    /*
     By content: a BASIC listing is tokenized, text becomes a PC-1600 ASCII file
     (CP437, CRLF, `1A`), a file with a PC-1600 header is stored unchanged; anything
     else is an error.
     */
    SDE_DISK_PUT_MODE_AUTO = 0,
    /*
     A BASIC listing stored as an ASCII program file (`SAVE "…",A`).
     */
    SDE_DISK_PUT_MODE_ASCII_LISTING = 1,
    /*
     Headerless machine code, wrapped in a header with `start_addr`/`run_addr`.
     */
    SDE_DISK_PUT_MODE_MACHINE = 2,
    /*
     Stored exactly as given.
     */
    SDE_DISK_PUT_MODE_RAW = 3,
    /*
     Tokenized as a BASIC listing even if detection took it for plain text (the
     override for a misdetect); fails if it does not tokenize.
     */
    SDE_DISK_PUT_MODE_TOKENIZE = 4,
} SdeDiskPutMode;

/*
 Line ending for a de-tokenized listing (`sde_detokenize` / `sde_convert`).
 Ignored when tokenizing — `CR` and `CRLF` input are always accepted.
 */
typedef enum {
    /*
     Host default: `\r\n` on Windows, `\n` elsewhere.
     */
    SDE_LINE_ENDING_PLATFORM = 0,
    /*
     `\n` (LF).
     */
    SDE_LINE_ENDING_LF = 1,
    /*
     `\r\n` (CRLF).
     */
    SDE_LINE_ENDING_CR_LF = 2,
    /*
     `\r` (CR) — the PC-1500's own line terminator.
     */
    SDE_LINE_ENDING_CR = 3,
} SdeLineEnding;

/*
 How a `#SEGMENT` marker line tokenizes (`sde_tokenize` only; a device saving
 multiple GOSUB "LABEL" program segments together). `Wire` is the 3-byte sequence
 `0xFF 0x00 0x00` actually sent over `SAVE "COM1:"`. `Memory` is the bare `0xFF`
 the ROM's own serial receiver actually stores into the program area -- use this
 when building bytes for a direct RAM poke rather than a real/emulated serial
 transfer (confirmed against a real PC-1600's `LOAD "COM1:"` pointers: BASPRG_END
 comes out exactly 2 bytes short of the `Wire` form, once per marker).
 */
typedef enum {
    SDE_SEGMENT_MARKER_WIRE = 0,
    SDE_SEGMENT_MARKER_MEMORY = 1,
} SdeSegmentMarker;

/*
 Volume geometry. Only the CE-1600F floppy side is implemented; a RAM-disk card would
 read these values from its boot sector instead.
 */
typedef struct Geometry Geometry;

/*
 One directory entry.
 */
typedef struct {
    /*
     `NAME.EXT`, NUL-terminated.
     */
    char name[13];
    /*
     Attribute byte (bit 0 write-protected, bit 2 hidden).
     */
    uint8_t attr;
    uint8_t month;
    uint8_t day;
    uint8_t hour;
    uint8_t minute;
    uint8_t second;
    /*
     Size in bytes as stored (a header included).
     */
    uint32_t size;
    SdeDiskKind kind;
    /*
     Machine code only: 24-bit load / run address (bank in bits 16-23).
     */
    uint32_t load_addr;
    uint32_t run_addr;
} SdeDirEntry;

/*
 A directory timestamp. The PC-1600 clock has no year.
 */
typedef struct {
    uint8_t month;
    uint8_t day;
    uint8_t hour;
    uint8_t minute;
    uint8_t second;
} SdeDiskTime;



#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Crate version, static NUL-terminated string.
 */
const char *sde_version(void);

/*
 Last error message on this thread. Never NULL; empty string if no error.
 */
const char *sde_last_error(void);

/*
 Release a buffer returned via an `out` / `out_len` pair.

 # Safety
 `ptr`/`len` must be exactly what a prior `sde_*` call wrote, and must be freed once.
 */
void sde_buf_free(uint8_t *ptr, size_t len);

/*
 Detect the content kind of `in`. Writes `*out_kind`.

 # Safety
 `in`/`in_len` describe a readable buffer; `out_kind` is a writable `SdeContent`.
 */
int32_t sde_detect(const uint8_t *input, size_t in_len, SdeContent *out_kind);

/*
 ASCII BASIC bytes -> tokenized payload. `with_header != 0` prepends the serial
 header. `segment_marker` selects how a `#SEGMENT` line renders -- see
 [`SdeSegmentMarker`]; pass `SDE_SEGMENT_MARKER_WIRE` for the previous behavior.

 # Safety
 Pointer/length pairs must describe readable buffers; `name` is NULL or a C string;
 `out`/`out_len` are writable.
 */
int32_t sde_tokenize(SdeDevice device,
                     int with_header,
                     SdeSegmentMarker segment_marker,
                     const char *name,
                     const uint8_t *input,
                     size_t in_len,
                     uint8_t **out,
                     size_t *out_len);

/*
 Tokenized bytes -> ASCII BASIC (UTF-8). Accepts a CE-158 / PC-1600 header (device
 then taken from it) or a bare payload (uses `device`). `line_ending` sets the
 listing's line terminator (`SDE_LINE_ENDING_PLATFORM` = the host default).

 # Safety
 As `sde_tokenize`.
 */
int32_t sde_detokenize(SdeDevice device,
                       const uint8_t *input,
                       size_t in_len,
                       SdeLineEnding line_ending,
                       uint8_t **out,
                       size_t *out_len);

/*
 Content-driven convert (mirrors the CLI): picks direction from `in`. Writes
 `*out_kind` with the detected input kind when non-NULL. `line_ending` sets the
 line terminator of a de-tokenized listing (`SDE_LINE_ENDING_PLATFORM` = the
 host default); it is ignored when the input is ASCII BASIC.

 # Safety
 As `sde_tokenize`; `out_kind` is NULL or writable.
 */
int32_t sde_convert(SdeDevice device,
                    const char *name,
                    const uint8_t *input,
                    size_t in_len,
                    SdeLineEnding line_ending,
                    uint8_t **out,
                    size_t *out_len,
                    SdeContent *out_kind);

/*
 List the files on a side into `entries` (up to `capacity`; `SDE_DISK_MAX_ENTRIES`
 always suffices). `*out_count` receives the number of files, `*out_free_bytes` (if
 non-NULL) the free space. An unformatted side is `SDE_ERR_NOT_FORMATTED`.

 # Safety
 `side` points to `side_len` readable bytes; `entries` to `capacity` writable
 entries (or NULL with `capacity == 0`); `out_count` is writable.
 */
int32_t sde_disk_list(const uint8_t *side_buf,
                      size_t side_len,
                      SdeDirEntry *entries,
                      size_t capacity,
                      size_t *out_count,
                      uint32_t *out_free_bytes);

/*
 Read file `name` (`NAME.EXT`, case-insensitive) from a side, converted per `mode`.
 `line_ending` applies to listings and text in `Auto` mode. `*out`/`*out_len` receive
 a buffer to release with `sde_buf_free`; `*out_kind` (if non-NULL) the file's kind.

 # Safety
 As `sde_disk_list`; `name` is a C string; `out`/`out_len` are writable.
 */
int32_t sde_disk_get(const uint8_t *side_buf,
                     size_t side_len,
                     const char *name,
                     SdeDiskGetMode mode,
                     SdeLineEnding line_ending,
                     uint8_t **out,
                     size_t *out_len,
                     SdeDiskKind *out_kind);

/*
 Store `input` as `name` on a side, converted per `mode` (see [`SdeDiskPutMode`]).
 `start_addr`/`run_addr` are used in `Machine` mode only (24-bit, bank in bits 16-23;
 `run_addr == SDE_DISK_NO_RUN` = no auto-start). `flags` may contain `SDE_DISK_FORCE`
 to replace an existing file. `when` is the directory timestamp, NULL = now (UTC).

 # Safety
 `side_buf` points to `side_len` writable bytes; `name` is a C string; `input`/`in_len`
 describe a readable buffer; `when` is NULL or readable.
 */
int32_t sde_disk_put(uint8_t *side_buf,
                     size_t side_len,
                     const char *name,
                     const uint8_t *input,
                     size_t in_len,
                     SdeDiskPutMode mode,
                     uint32_t start_addr,
                     uint32_t run_addr,
                     uint32_t flags,
                     const SdeDiskTime *when);

/*
 Delete `name_or_pattern` (`NAME.EXT`, or with `*`/`?` wildcards) from a side.
 `*out_deleted` (if non-NULL) receives the number of files deleted; no match is
 `SDE_ERR_NOT_FOUND`. `flags` may contain `SDE_DISK_FORCE` to delete write-protected
 files.

 # Safety
 As `sde_disk_put`; `out_deleted` is NULL or writable.
 */
int32_t sde_disk_delete(uint8_t *side_buf,
                        size_t side_len,
                        const char *name_or_pattern,
                        uint32_t flags,
                        size_t *out_deleted);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SHARPDX_H */
