/* @generated by cbindgen from src/ffi.rs — DO NOT EDIT. Regenerate via `cargo build`. */

#ifndef SHARPDX_H
#define SHARPDX_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#define SDE_OK 0

#define SDE_ERR -1

#define SDE_ERR_PANIC -2

#define SDE_ERR_ARGS -3

/*
 Detected input content kind.
 */
typedef enum {
    SDE_CONTENT_UNKNOWN = 0,
    SDE_CONTENT_ASCII_BASIC = 1,
    SDE_CONTENT_CE158_BASIC = 2,
    SDE_CONTENT_PC1600_BASIC = 3,
} SdeContent;

/*
 Target machine family.
 */
typedef enum {
    SDE_DEVICE_PC1500 = 0,
    SDE_DEVICE_PC1600 = 1,
} SdeDevice;

/*
 Line ending for a de-tokenized listing (`sde_detokenize` / `sde_convert`).
 Ignored when tokenizing — `CR` and `CRLF` input are always accepted.
 */
typedef enum {
    /*
     Host default: `\r\n` on Windows, `\n` elsewhere.
     */
    SDE_LINE_ENDING_PLATFORM = 0,
    /*
     `\n` (LF).
     */
    SDE_LINE_ENDING_LF = 1,
    /*
     `\r\n` (CRLF).
     */
    SDE_LINE_ENDING_CR_LF = 2,
    /*
     `\r` (CR) — the PC-1500's own line terminator.
     */
    SDE_LINE_ENDING_CR = 3,
} SdeLineEnding;

/*
 How a `#SEGMENT` marker line tokenizes (`sde_tokenize` only; a device saving
 multiple GOSUB "LABEL" program segments together). `Wire` is the 3-byte sequence
 `0xFF 0x00 0x00` actually sent over `SAVE "COM1:"`. `Memory` is the bare `0xFF`
 the ROM's own serial receiver actually stores into the program area -- use this
 when building bytes for a direct RAM poke rather than a real/emulated serial
 transfer (confirmed against a real PC-1600's `LOAD "COM1:"` pointers: BASPRG_END
 comes out exactly 2 bytes short of the `Wire` form, once per marker).
 */
typedef enum {
    SDE_SEGMENT_MARKER_WIRE = 0,
    SDE_SEGMENT_MARKER_MEMORY = 1,
} SdeSegmentMarker;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Crate version, static NUL-terminated string.
 */
const char *sde_version(void);

/*
 Last error message on this thread. Never NULL; empty string if no error.
 */
const char *sde_last_error(void);

/*
 Release a buffer returned via an `out` / `out_len` pair.

 # Safety
 `ptr`/`len` must be exactly what a prior `sde_*` call wrote, and must be freed once.
 */
void sde_buf_free(uint8_t *ptr, size_t len);

/*
 Detect the content kind of `in`. Writes `*out_kind`.

 # Safety
 `in`/`in_len` describe a readable buffer; `out_kind` is a writable `SdeContent`.
 */
int32_t sde_detect(const uint8_t *input, size_t in_len, SdeContent *out_kind);

/*
 ASCII BASIC bytes -> tokenized payload. `with_header != 0` prepends the serial
 header. `segment_marker` selects how a `#SEGMENT` line renders -- see
 [`SdeSegmentMarker`]; pass `SDE_SEGMENT_MARKER_WIRE` for the previous behavior.

 # Safety
 Pointer/length pairs must describe readable buffers; `name` is NULL or a C string;
 `out`/`out_len` are writable.
 */
int32_t sde_tokenize(SdeDevice device,
                     int with_header,
                     SdeSegmentMarker segment_marker,
                     const char *name,
                     const uint8_t *input,
                     size_t in_len,
                     uint8_t **out,
                     size_t *out_len);

/*
 Tokenized bytes -> ASCII BASIC (UTF-8). Accepts a CE-158 / PC-1600 header (device
 then taken from it) or a bare payload (uses `device`). `line_ending` sets the
 listing's line terminator (`SDE_LINE_ENDING_PLATFORM` = the host default).

 # Safety
 As `sde_tokenize`.
 */
int32_t sde_detokenize(SdeDevice device,
                       const uint8_t *input,
                       size_t in_len,
                       SdeLineEnding line_ending,
                       uint8_t **out,
                       size_t *out_len);

/*
 Content-driven convert (mirrors the CLI): picks direction from `in`. Writes
 `*out_kind` with the detected input kind when non-NULL. `line_ending` sets the
 line terminator of a de-tokenized listing (`SDE_LINE_ENDING_PLATFORM` = the
 host default); it is ignored when the input is ASCII BASIC.

 # Safety
 As `sde_tokenize`; `out_kind` is NULL or writable.
 */
int32_t sde_convert(SdeDevice device,
                    const char *name,
                    const uint8_t *input,
                    size_t in_len,
                    SdeLineEnding line_ending,
                    uint8_t **out,
                    size_t *out_len,
                    SdeContent *out_kind);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SHARPDX_H */
